---

- hosts: all
  become: true
  tasks: 

   -name: update repository index
    apt: 
      update_cache: yes
  
   -name: install apache
    apt:
      name: apache2
      state: latest
      
   -name: update repository index
    dnf: 
      update_cache: yes
  
   -name: install apache
    dnf:
      name: httpd
      state: latest
